---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  #- name: test
  #  image: node:12
  #  commands:
  #    - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker 
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-record-matching-finder
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: BLQPNGt9aBgH45vtC+pepKG880coFqv2/GCVNgjLMHgbjsE5m/2ZOnEdONzGRMZIuhg=
---
kind: secret
name: docker_password
data: C4THHoBbEqZRZVT/IRlJswnm+kbpqdXGmcfS5x8vbJnLWn4XRjKJSLTpnclR3jVBW1/oDQ1bSKJWe1m3TqVppeBfZSRW6P1QqmV0hmoLdKXByTLinAkotdxPjcE=
---
kind: secret
name: ssh_key
data: fy1aLocLNPMZN6l3FTgTV59OFplAHkK3+E5dkca5sSUCzuqA0HeEEzrX0xJ2nmtgKSBYGnDXKvbWCl0IGW1WUftJXbX4X9qbgLF+PTZtXHFpbHUYAvHsW9KvupNd0Qk2c9HvE9q1zyKodXtQXKIooOKmE94eydYw0wmTkOV5IxeQt/otPVhXSl/Ty+rLyfB46KqLMQ9M0qrBSDXshzaOuQBizhp1xo916Io+Lst0aLBpCPHdtVttXCmPuEhlb2aVgPuQMcvTQMwajnPbVrh0n3R3p5CaHbMObF41hCa19nOv5aJP5XWzbrvFaIuvZVvqyswdHyEh04RY6SMPk8KTfKgpIc093/60Pesa0GhHlFfew7dt0LrEdHqLHVOXuYFK8nK0oWT00yqN8FJ/9Y4vBJkLu3cHPgV6xDM+evbVk0hrwks+oGFL94iFD54cVHOSTfTHInMRKPOeNOs0UQ4RmgK6qda6xwg9ftkkPsghsUTu+3Osu730Dy4lUIC2KKw7VpeQMTCyto7l7rEwWiq09iCIVPRMWpguPA5MFBP5ijuFe3l+nwktJfQe5ScvEygXcAbgFZfDg9nDY0IpGYQbeDcWVqGCCix87bhps4koAA3liDh6mB4E+sFPSWwyg76Iq4OIGR48crEnqDREEkT1pMeywtzbcIKyQkclc+pf/RPUhe+f0eOY9hPS1vbsaJbO8S6I6sCpLTKgXgJHtSArrYAHVfZjRpR/h5++Hjv6OyJle7y9p8d4Ch9mHPHjpbdT6f8SvTWoMOpbITo6DgAoP4q3vdPaz2ukMnWor5UvnhB6iT3NIGqxvCfQTVSwGGDhoUJDQ8oMKlGpyaSGIe2Q+kIRREylmiF07Vcl9V9VIX+v2jqi5ZimG9mKxeCHZnb8fILvJCY+pxcg7zHB/kOjjjD4l2fLgrDJOW2GQIYxxPskk4Hyhwo5BoCS8l2k/jF0GVBDglTSMdqZjRc8/dTNN40eGf5TGNmH4/eSBsoz/7dSisIXx7/2yt3lhpNJjqVc+5pEFo6BEeLhRl/5C54cS1P8DVgSiR0vPZj1B+PBbbxkghC6RZyUyfqXXyofXour8hlHj4UdA25xkYV03aCBtikEW/0FrvckrwioM/Fy3LBWe1NzWF/buNVmfEMvFff2DXnvBLdHc7CE9CKE4NoVSSkvSvOCdimrPAr2WflwDr1iVNJBepJqcUKRUvPhfM4FH8lrXg/LJQn6WcYXmVtk5JQ7rb6WJvxiGluaDnJJGYDt8BLf3aoidw8tSdSc0mYmBrhg00YN2cfTukV05K6HG+jZ2fW18fibtHwDFYiFlCmKiMjdtrdURl93IkoWqEtq18njzVtWOMHBWcdrMkSKsJ/ja8Iv7f/WrT1P7np38Fx7hsFqBYCbBeV83TT4AhxmMrpWsVOeAPci/77p4nSm0+s/nEwWRsUME8ggLigzdP3859sARFnEmGvAdVV+1k0oGpA9lPw7lqSHkGtEYpVNSEfg2xmy0Czvh5qzlh0JZPTfrfgX/XH3zTKXU61FQHA5LZkHCIqptsFYE5L6dNnwCzAbiNsQJrTRsmvLOhF5NVRlpEIir9iGTzSMvUtfTiSXAMKz9bX7ruTcdTRden0FlCSO7JTzwpxn+j9yEXMeJYWZdZ+sWOhYEX+QKk9PuHWhCybo3EvXMj3EKKlSP6ov32fzY2oE8+HoNFh5ErjnpSlPoNVR54yUOwnV6K9/70zQSSoAM+xgFX5/cAXBjyBjVcb0AqmTk1gArYehnHrrabZraXK0eetn0B8r0m1cli63dhGGZoh8BP7evAY1Oa3GNI35GhFPvoXnk0cBrdsy/NPi/TLKEk9zjy6UEOk4sjEtdPvgIJx8D8yzdvPGtBAZ3oumqpRejyax50BAGQdwKJqg7b5Qnsb8w44OzdSx6yQ93RTZn/hNuaKn61OPM1P/DkVql0/m94slA+9zBGY96Sgbe2vzN6UjIYkK71OWBOzCvCWIIb4EdKtYEcBy5DoFRFnShwepY6u6eToyTqmtK+/pDhkN5Zk0JV4Rq2zNbihk3BkdzgyrBKOrCB4gNTnlFuFlPwINDoB6NRKdk7vVES+fen9ujygXgk7/eUSk4es+Rcf7SQT3WBqCXxHYe9O+ei7V6F4ea/oe4JDzsiHBZWQI6lVmgelF1uMHi41rPQCWVBnguT05PJqfw3+uTVmepefbchTHkayMZDnCYkg/Yn1C2STQY1jErkyKVtMLNWrzn+UM/Xu80WS9PX1bnpOPi1Ckv6japGkJQokXXqcUbID2tFpv/ZXxiavq/Y7rmXX7gjxwcnGsY2fTZ1U0bDfeulcIRk0noI+Z8JC8no4sqOXAlbsDlUzvl4lj5CyxQA/YvuPXqVqPYn4se5DYUnXQ/NNQox9KU4Yu1GYwgnBH6HnPXlSETSFAgFWdKHdhsWUw73RTsRTnZXAgrVd3v2RDsYrk4gj01nRS0wCuuCmsVbqkJXNDim21G0mF6quUTRzEm+0Ow+w38cDej4VnEz3vnLxRoG7xVyh+i0MhSQ/gPjmNueuyear2iVKl1ZAEE0+naF6fIN3u+s8H/bcw1hGNMdtFRJTmog4Sn2B+AlOqr9HrtwVKStBk8VV/5cQUCLDbNR5dMnzFed7T8iCD8zJ70fBK1/NPmQS8nuaLKS2VtzikOs0epuIfniyMT2Hyrl4yr9+6oydvveYasWZHrXHmqC7svCRPlVVxhCYBzlEZZDjve9mKU5fSxk0QppMjwVTbT6uUvpHcr5jLCtAzvAFxQK/LE7ugnZZD7K9mLqspxKId3rdoxp90GeJsoFM8z9vCwOtLqZhxq7638FPe/+LdYiVSyT3dO4T2gRnWa/Jqp/ZmR6mUn1gF1MQzzAGFFXddBOapmyRfZUwZhK2yz5VnROyvzXzk2iLpbByGnQSkDChK5jyfNSfJlDVXcc3lbrwWjifg9RCo2dSPQWFBqEPqIWerj4UDQOJgFh6m+n/Sr23IN8Jyd5UCYkasVFdKQ3u1aL53tu3KAF4O6d0m
---
kind: secret
name: gpg_key
data: /RXNouLTm9GTc8Crl1yDMs/q1x6zBWPkpijkV8vp+srKw+nIJbq1WiJOk1NwsPJep0ECNfvIgFaeusRCB3nmEnIMq1b5fKs48tTvtUA3zEfgiAAeof2Lwn3GRL+BwMsmfEoab4yb2v7nNQiB2ZbTAF+euS292iQoi8N1vqxrryg43jfBoMqCdwU4q3bm4H4+IfIxeGVWgkT2gUSAXggmjriboz1VhTwHvEuDpSbN8Eda8uV1qC+xWpD7116xmrNYXe+tJ1+D6csOOPHQzx2f38htLhWyb2oBULg17MRV40oxzcQPVXOBmp3j2GgOsJllnD76lksgZlKGk/y13qWXxtoRSnxC4Ks4YK687D0tJ2rDP2f3ZKSawUiIF1veVt9HHqAQ/cfsTkoxOdcu4v9cjniqHmoN6bbN3In0fKXAe4UCN36j+y/ErTmN4h8lN3BsJ2U5U5yp4/+WjLWKphx+mTBylNvdpdggOWFGtlUu802TbJjcOIAYqIBKaFs59MDSIQtCJxfVNruui2Q2HeAgZDFokR5763ZveY7VM37O4R+jAsqQrAEmuBBopdo/KW0EPLM9x0R5E2Saefv+VDQfHo82Yj0Ifrg4b0UfJfYUqS3EkW+2SedQX0OrPu8rqdPjRtqRUK9BUoxvlsHT9FVDvZIydIlTx5tdAvGgV5d+OrRUY5V0bjNDCOMenRkf47fhs7wrkrMr1klEC0Z9A5/qrCPdnUbiPjc8g+1XykNBQ52jS7K4KgjzRRbTtmEYKmezFG1p9h+7ett66/rCmUjiWZUMbRyhFEPEidn4wqFVAmu1Cj+0ZDylnBK9NcFs706c6d4QBvavI2wF5ZGX7YS1mFAioJAd129wTMGR/lkSeOWufd23GXb3YhncgJ0bNrjsMx1UF8vbgxh/J+CgO+8ujI0nmQhzIqXQ8NP/Rbu+I00hwFdkiRLkhK7q7O7xFI9vbgra+0AYf9WPk96Bl5uYnZHF88aiBERE2vHKQUUBdekYnYB7gshBCaeX5rekTsnJ4PXZ1fEJFUqGDHL17WrWK6sBySoGbu53Hrduy86T9PO1QLz10oMW/GyHIDU8zK7+k2pNBqRF3qBz8TVB9jOlLBLrzgAX2xrJn69AF78+MaUSb9/RTnKQ3ApVdYtP4LgdrwjQeChzRk18LGxVTKxkv5DHoYFcMVSy0OcFSvTK/qn5+Cw0Au1cN3Gjf2hseWBq++Tr7ry+NPAtbHax6bxQfHUYIEofXyuElMgNNLJ6bd2lWWI4btYybJ+YDSqaSEuaDelfuLXVc9q2r0zxva4vvlchmtjRc0l6nWIvBZ+mg7e/m0wjA0yRD3zk/8MQ+hRAo+nHdvRx/WdMcNTUP3gy0sRELet9WEp8mt1aIb9lMODm9GMD4RMMfn6lgvgtW1cXqFHd01EZtGIXTyUePSEgzQIQSOGZC8L/EpXQGt4F3w1FWNt0xjnoSDgEy6Mf6Id6TYDHiyb4Gn2iQFerRlL4FMwW1iScaKb00WOwmcmjiHYa98vqCnk7S7/Qwj17oOoUtxR1pwCUpreuACKyRGZdkfs2hIfDTazKjMhkGq538plYZw8vrkpGuMaU2FlAidg6UdTdlrxGq5Gx81H6F006W7ir+AMs+W8dRU6QMSQTUZ6G/4bMjarRDZuwEYVHVLf6SGIR6FHuJYjA1x0llDZFKuQChaNRTG63zcLhC0oT9X83N4+kWxJJOHyLeE7+F7/KBy8A/wuQ7Q8iFN41Gm9S4n/yT17qps2VJJ0PzXEu4NNSuMNDD92ke8iRXpBGL+7j14F54KQcZeCjJslaU1osTsLvqTSX1SH/ofOroNQxjobJNF+XhXdsJGnxrHoD/B+GrY3lVJr/82NQvc5rYX/bE2U+GoYGRIg4h0PynycOy+Eig/FoW8Nbh8o4rWTvjt4vqFVkiEKKZnT0+tPwUV8JOJMBXPQYkCMWRPgFjkYboImHWk1Iz10pDRMl5l2K4wIYti3xGViBC3FOcuf3YXtodhB/Za+svnHzzmS/VIe9NPFAFol8EEibTCEmI76XFSandIeZ4HIzp1DAiW8TrJzX2YVU9S8h6Wmfh4lXevpTM+IZZme236PBLa4XHIpS0gMsiz4QRZIeqen1oW+hTnc1NrMYFoAzrvQ82TWp0ryRmUfGNY3Ah65F3ic864Z3ZZdyiwvZueTiZTKAujH7vyRI8kPcEt9gINbLKZnpdLCpgkjuwMclthWyCM2VeFwjtXmkkeleAZu0dDPbMPh3wmtIUJ7RoBZuHHteeHlPJz2NMnmBj+LTVoGHTluZ/11x/6ClAisuqo6uZnpt5bcnZHnOIRqLsokJ1xaWT/4oXWvjiVvqjkrPf0EwLpiI3Ys7GDGoacPUEvDqD4FPd6N3VeoMjD/Z+dlcg0lJa6RboxdnROjpK+ImbmTaFYwinysoeLL21oakeqW9b4j5LolN0QoOvV5TocO9VLe4Im3jd6IMvnQUlf3NKFdsXOpvptOWJxFs4eoA8aUuKvGmqN2PPeCZghRNSEmHj86W+EFi/i2iOPlfwgXiHe8WFdNaw8pBZ1G1EK0V7Zk6ZXvON3Zklge4yba9LEQ3iffJNQMW9qyBbt98fC6RSGX/tBuOmCW1MWGtqNR0Ay6cjnLG1ENSQM+p38qW9Idijcw5gswMcrqx3xaaVYhhZOrCyOrOSHDu/ZSyqROh3Z37oLhiqrlo+eeGD/8rQrFikI4swJdKi+rsQFbZT1hFyIN8rqJLtLaVVNRiQAa64hY56BWEIu+7twysM/7r7OXyMpjwFWNBBWNN6vbnVKxWUJi88NN2idkNvJJ3AMf/UMqeW7zd4YdqTk9p6BW6N9LM18wgYzD0IS0cKvolKF/Xo4XFhZBSfNoXdhJv9wk64IBnCm9Up9HZ6W0hbCo5tBkifSYsimCNuGhZsE4RCV3f18Ttb02f8fxqDwL8HlwNKnWrtocneyu8QrE7jcLlUi10NxqIV2IfjEa9NDtHSG0csUd+X5p3Tp72Yb+1tCPMnF9dbgDCuNPr8+9speGxrNsct/sXbTZCgB7FABB5cp9eumDQdEhIypP0kcd+uo2iUZxM36RChrL8w3qJh58bTMyqofnWMU68ADRAd71C/VzYJtARQ8x6qbcUV41ZbnFrXeV/VZIgDSzN5ahtVMbeuPtoEsMH2lnGxpKaR2h/59Ch3459/v1xrb2VMpC8aJHKWS/F/QmlYrHSj7hSBNcEbI4fbaPsXhVq/037KHXxe3MRGbXOADzCvKdQzgJtycuOjLAPg1BJd+TsvPKxSydpWQwc7fpiymjxJkwAynCjumypzFfnqk5PGkR/y/8Jmgt7ACrufUUerNNq3AUUmQBo3wN8P+3jOyc65g07Su8lldNLHWFtagVAEGHM/UorDf82I2ap6tN1rqk6DPRRuaezQ3qoRtMFM2JKUjRqjdwo6XwoWMnjNAJjdA/hghJA493LoZfpr50NSh2r0b7gLnaNVbIS+UH1ZJJMsm639jBvET+DecrqmfTV1YTICNHXr3a2WM5zir9jhJ+ZDBVRqOPl1JLz35JbTmcWFu96P48aLsh8CIPJUZw2oLG0plNOp6h0WiNtQjpdsPDqZmUe0NaGB2/BtIpgnaFiTp5+4Zm9uCslpJrXc5KhABskzi2QUrvcsBi/JTpl5RVFge4ifIqL9g52NCsjKGxHoNtOB+L3cKwqnx5/0iMUIxzna7CxcYKUkdeoS7OeJeytuV5cyLduU996F0ZkurpPwSwtxA2UmtEqHQqimD6cSHyZwxJjNRwe8SuZtve5LCJNzTdMAdwE953E4CtxxSG8f/8tm364zCnB5c+9JGC7l4dvqPDYf1ycATgiG8QzZzIrB/C4mz6GxMPfrYyA8VT4GNAWJe7hJfOnySuKO2qGM7Cylnp+vWcICH5jh6Y3ad1yjKgNPFiT39YUUTVL6Ukyy/z2zTHLBUb9ohsZoDJ0Wc6C/vZJ43CG1awYmBS8ObxZgW1chhdxrsQA9h4aNqHlQF0Zq8Uh6c5OrVa6Vx0dzMIwOfhGAIzM4B9NwcI6b5+wIYnoA/rdw8cCiBDIrNMShuOABLsm/WK892byCbpzfInVQYZsQwxj9gglhYGI/mXpzEn0fC/quDwUE0/E7CBryVykOBpCmhfpXnRhySLCabTlDVOUyngxLTBwr7l81rm6WRzLJJpb50/fZhLkGY5nyep2HJfxeNcKqhDvUyF9nVEx/KROf7Ld13tqV2LA3Gf9WfCT8IvR+2aRMuKJyoNEsrpSE8Cu/6m4n16jm0WhnFV37Om8VMFpCU1GDI+RYbr9NCqhsKak82/AlI6mRX73Nbb5txabiMxxevi3dFl0KPFpLZ32g/3uRbte1eLiIlftVK1Rwh7mt0HVuzf352V91GAICm2AwPAeTmcvjx4dMqoDxWoC0u8aGrfQKmAziuFoQhZkcreYRR0U89vz105e4LuRMDkeocUPlyPEhEVAw2iAa2I1164Mvqzo8ID5xotEhNBv8SfPWk7wC84MfAcHDtNO8zxigEkSYiAIFkUO61+WICpI2DhUrG8RItCfRRNMta0Oxx5a47CqkaUhIp5GP22BYsxZl3rh/9Gnsire1xEWHh0JfBWcDais0rt/FsVlgsVtcIcg94fGIsi3wlMUIfOPV7HqrZPYbkVQ2AlAeaTCMsPkhcVWrnou+d2aRh1wQbrsdpBMuEbKljb8Coo32ZDPHvHHFXBYlkKY24FFXMg/iZawcIPxVMdOw3Ilu7DX8hZYzzeCd77qniuznJI8uB6eQZVBEv4HaaInBFF8WZfl7HaNF47BK0ix0IshLcAurTC3G6qkPTgszvvE06//pwoYi2WohItYS+iR0Dni1ksmXrU6m56lvFy67xRznHQVdCui8Qlo9uGQqnnn3dftRMJvnG/IOu3hj433+0J57ym2tuaKgcWs+J9wuxKecgUq4yey3j8474bkdA98V7t4CkJmdK8v25By90eGQC9zTU0topxFuGg38rap+ncb7Zrl8GHNApTh0AAa5sMjvhdjs7BhTG+24/Y00ImH8dcgQjXEvJQj1bX63BsYSBTI2f429qaUX5yyLv8H4PmWlt3c5qxibwKi+ZELnFpQDr1pH+5TdQjdmwNJP2QbKyVcXkzyR5DQpsDbENqfcmhx2ycoOJESA48kP2z8sO9yQynG4vFRAVnnhSmRk3Vsp/iN935U9sHBNie2aADmnKNqp4EjQdqjonmASOcucJ6oCsALlYncGSuuq4lHR+DVTkq9lRwnfNx70eGzj/K1dlM+V47Xz02EsiBkuVpPt1JcspJt1O1jpT2ErQqRJAFxcTnFcBJLk3cbk9qe9eXGliiZVvhmgo9zX/qOQIG71j7lTIvBGebFGhFGbx49zwjYoc2/bde6TXC5h9Z6FB+NMna27Uwxo6VK8hD2CPjteN5ktG0xqm5bwjxxu7vRnwVp+82efMZs1wx6+MF66CPycEDKZiy0IINGaGMt7fPuYS25nLGxYfZEuCisBJJlhHNWcIRLBBt0NIBMn/TmvU9eNVma8CRpNCJRSDcX197rUaqSY4KmP/sXJ5JwFucjADOgO9GVlrbGpzXzT6LIFSbW+bh31OfQIhMvKOEsc5YAI1emaXemYa10bci6tzSA/oz1Ez7o/n3CjfNCr22GHIIcZx2toj/CBZqnmfy5bnwngQSZ8x2vc3TTwp7V8HrPU+2olpCkOR1c+nW4tZX9PnJ8apAVrZG+XZI8ROZXYBn57W/mnYU3UPFg/H4Oyut9paAA2zRFqKXEuWaDGDS3kg8F2Yq/x7FZOPZzJ5C3U6m54U/wZjEl0W2i5g6R3cN1fI5gCtbomYQXOGcUaEDMxppjMu+vSmJD/6492f6aZvKBaSVb5Mlrh5TPfRWsfxwpHgB5A4VaMAKXhCIgF9rMQ5lYqgdP7p2iMoSSlI/hkb5YcQ/AT8ytkFur5jCRy3Vls0HV1GhQG3s6vN432Vy6YEULrQ4KquclUtTO7r+/LHGp6n9c/JtVg5s7jHXlPuBm99NtV1TcRxRAO3NxKZh4fO7cybsEQRQ+1HQsJoDTlgxE366eLADBOVZYC9PoPOnYfjhrFmfNVJc0oukSJ1eps9Z3sX465cbX2xwYOcAg294LfqtGPHUcirNh1+P6x9zMciFi7xtTgLD9ScaOWTcQN1d2Rzz13t/I2JQQVp7yiTazQL9f+KLx3QgT76qagT2DvwhF3Vc9vxylK62yitoiu229+JkKbvKcIs2JlgXykToDIB0cN8deajrOPorx9iC39ucwchLlvnlBcACObAbhGUHuMeLEuxI+J5eclVU5StNPAYW8XVlnupC445YEGxC7WyziXLzs2l0X4lA0iedvPMibHGDxtOrnd4y+4IPtljFuqO7visNsJFh4tNqsX05G3h/SHUhXDmKp0V6ScQEsKg3g3TOvV1NPA/kzVsh1p81DydraIXi4LPalszELJ66jg20ZNmPjrwgXbgWlcvhXd6X2ttAbYFSNzFBTPvmzPhMASGSCD8bOMzhc6BwvFN9VYJ/7VLDY49UQSW0CPK0PE8pa+KzYzHdfyQMVXH4bGRH7P+o8PbGb9DVm9+e0Brgi/bV00ZK7SaZzcR3DDZzBdAjLHIo5w8ybPpdXdo0I53hC75Lkn5m7tfCSp0pMpYGCsb/nQfBC2gySNGswmPz3dVJIQMn3emMwEfjDhSeU7PooUMClnA==
---
kind: signature
hmac: c76890a615f0cae48a79c3a0299a12c2973a6d504ae3030fde4760e86339594f

...
